name: webview_flutter_linux
description: A Flutter plugin that provides a WebView widget on Linux using Chromium Embedded Framework (CEF).
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 3.16.4

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      linux:
        pluginClass: CefWebViewPlatform
        dartPluginClass: CefWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: ^2.10.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^11.0.0

topics:
  - html
  - webview
  - webview-flutter
